#!/bin/sh

# quick-n-dirty script to rename the mobile build for tests

# rename the app title
test -f mobile/res/values/strings.xml~ || cp mobile/res/values/strings.xml mobile/res/values/strings.xml~
sed -e 's/IITC Mobile/IITCm Test/' mobile/res/values/strings.xml~ > mobile/res/values/strings.xml


# also, you'll need to build with
#  ant -Doverride.package.name=com.cradle.iitc_mobile.test ...
# or similar
