source 'https://github.com/CocoaPods/Specs.git'
pod 'InAppSettingsKit', '~> 2.6'
use_frameworks!
pod 'RxSwift', '~> 2.0.0-alpha'
pod 'RxCocoa', '~> 2.0.0-alpha'
pod 'RxBlocking', '~> 2.0.0-alpha'
pod 'MBProgressHUD', '~> 0.9.1'