// ==UserScript==
// @id             iitc-plugin-portals-exporter@ZasoGD
// @name           IITC plugin: Portals Exporter
// @category       Misc
// @version        0.1.1.@@DATETIMEVERSION@@
// @namespace      https://github.com/jonatkins/ingress-intel-total-conversion
// @updateURL      @@UPDATEURL@@
// @downloadURL    @@DOWNLOADURL@@
// @description    [@@BUILDNAME@@-@@BUILDDATE@@] Export portals. Generate a kml structure to import into Google Maps or Google Drive.
// @include        https://www.ingress.com/intel*
// @include        http://www.ingress.com/intel*
// @match          https://www.ingress.com/intel*
// @match          http://www.ingress.com/intel*
// ==/UserScript==

@@PLUGINSTART@@

// PLUGIN START ////////////////////////////////////////////////////////

  // use own namespace for plugin
  window.plugin.portalsExporter = function() {};

  window.plugin.portalsExporter.escapeHtml = function(text){
    return text
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
  }

  window.plugin.portalsExporter.box = function(){
    dialog({
      html:window.plugin.portalsExporter.contentBox,
      dialogClass:'ui-dialog-portalsExpBox',
      title:'Export portals....'
    });
    window.plugin.portalsExporter.kmlGenFromMap();
    $('#portalsExpBox').tabs({active: 0});

    if(!window.plugin.bookmarks){
      $('#portalsExpBox #convGmCb').html('Download "<strong>Bookmarks for maps and portals</strong>" from <a href="http://iitc.jonatkins.com/" target="_BLANK" title="Go to the site">iitc.jonatkins.com</a>.');
    }else{
      $('#portalsExpBox #convGmCb > ul').html(window.plugin.portalsExporter.bkmrkPortalFolders());
    }
    window.plugin.portalsExporter.setupJS();
  }

/***************************************************************************************************************************************************************/

  window.plugin.portalsExporter.kmlGenFromMap = function(){
    var kmlHead  = '<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://earth.google.com/kml/2.2"><Document>\n<name>Blan KML</name><description><![CDATA[This code are generated by IITC Portals Exporter plugin]]></description>';
    var kmlStyle = '\n<Style id="styleResistance"><IconStyle><Icon><href>http://maps.gstatic.com/mapfiles/ms2/micons/blue-dot.png</href></Icon></IconStyle></Style>'
                   +'\n<Style id="styleEnlightened"><IconStyle><Icon><href>http://maps.gstatic.com/mapfiles/ms2/micons/green-dot.png</href></Icon></IconStyle></Style>'
                   +'\n<Style id="styleNeutral"><IconStyle><Icon><href>http://maps.gstatic.com/mapfiles/ms2/micons/red-dot.png</href></Icon></IconStyle></Style>';
    var kmlEnd = '\n</Document></kml>';
    var kmlMarks = '';
    var numPortals = 0;

    filterVal = {};
    $('#convGmFilt input').each(function(){ filterVal[$(this).val()] = $(this).is(':checked'); });

    for(var guid in window.portals){
      // Get portal name and coorditanes
      var d = window.portals[guid].options.details;
      var team = d.controllingTeam.team;

      var ok = false;
      if(filterVal.enl && filterVal.res && filterVal.neu){
        if(team == 'ALIENS' || team == 'RESISTANCE' || team == 'NEUTRAL'){ ok = true; }
      }
      else{
        if(filterVal.enl && filterVal.res){
          if(team == 'ALIENS' || team == 'RESISTANCE'){ ok = true; }
        }
        else if(filterVal.enl && filterVal.neu){
          if(team == 'ALIENS' || team == 'NEUTRAL'){ ok = true; }
        }
        else if(filterVal.res && filterVal.neu){
          if(team == 'RESISTANCE' || team == 'NEUTRAL'){ ok = true; }
        }
        else{
          if(filterVal.enl){
            if(team == 'ALIENS'){ ok = true; }
          }
          else if(filterVal.res){
            if(team == 'RESISTANCE'){ ok = true; }
          }
          else if(filterVal.neu){
            if(team == 'NEUTRAL'){ ok = true; }
          }
        }
      }

      if(ok){
        var lat = (d.locationE6.latE6)/1E6;
        var lng = (d.locationE6.lngE6)/1E6;
        var namePortal = d.portalV2.descriptiveText.TITLE;
        var styleType = 'styleNeutral';
        var address = d.portalV2.descriptiveText.ADDRESS;
        var imgUrl = d.imageByUrl.imageUrl;

        if(filterVal.clr){
          switch(team){
            case 'RESISTANCE': styleType = 'styleResistance'; break;
            case 'ALIENS': styleType = 'styleEnlightened'; break;
            default: styleType = 'styleNeutral'; break;
          }
        }

        if(namePortal != undefined){ namePortal = window.plugin.portalsExporter.escapeHtml(namePortal); }
        if(address != undefined){ address = window.plugin.portalsExporter.escapeHtml(address); }

        var insertCoor = '';
        var insertAddr = '';
        var insertImag = '';
        var insertDesc = '';

        if(filterVal.coo){ insertCoor = '('+lat+','+lng+')<br/>'; }
        if(filterVal.adr){ insertAddr = address; }
        if(filterVal.img){ insertImag = '<br/><img src="'+imgUrl+'" width="200">'; }

        if(filterVal.coo || filterVal.adr || filterVal.img){
          insertDesc = '<description><![CDATA['+insertCoor+insertAddr+insertImag+']]></description>';
        }

        var kmlMark = '\n<Placemark>'
                +'<name>'+namePortal+'</name>'+insertDesc
                +'<styleUrl>#'+styleType+'</styleUrl>'
                +'<Point><coordinates>'+lng+','+lat+',0.000000</coordinates></Point>'
              +'</Placemark>';

        kmlMarks += kmlMark;
        numPortals++;
      }
    }
    var kmlFull = kmlHead+kmlStyle+kmlMarks+kmlEnd;
    $('#portalsExpBox #convGmCm textarea').text(kmlFull).attr('disabled', 'disabled')
    if(typeof android != 'undefined' && android){}else{ $('#portalsExpBox #convGmCm textarea').select(); }
    $('#portalsExpBox #convGmCm > h3').text(numPortals+' portals');
    if(numPortals == 1){
      $('#portalsExpBox #convGmCm > h3').text(numPortals+' portal');
    }
  }

/***************************************************************************************************************************************************************/

  window.plugin.portalsExporter.kmlGenFromBkmrk = function(folders){
    var kmlHead = '<?xml version="1.0" encoding="UTF-8"?><kml xmlns="http://earth.google.com/kml/2.2"><Document>\n<name>kml-blank</name><description><![CDATA[]]></description>';
    var kmlStyle = '\n<Style id="styleNeutral"><IconStyle><Icon><href>http://maps.gstatic.com/mapfiles/ms2/micons/red-dot.png</href></Icon></IconStyle></Style>';
    var kmlEnd = '\n</Document></kml>';
    var kmlMarks = '';

    for(i in folders){
      var bkmrksList = window.plugin.bookmarks['bkmrk_portals'][folders[i]]['bkmrk'];
      for(idBkmrk in bkmrksList){
        var name = bkmrksList[idBkmrk]['label'];
        var coord = bkmrksList[idBkmrk]['latlng'].split(',');
        var lat = coord[0];
        var lng = coord[1];

        var kmlMark =
            '\n<Placemark>'
              +'<name>'+name+'</name>'
              +'<styleUrl>#styleNeutral</styleUrl>'
              +'<Point><coordinates>'+lng+','+lat+',0.000000</coordinates></Point>'
            +'</Placemark>';

        kmlMarks += kmlMark;
      }
    }

    var kmlFull = kmlHead+kmlStyle+kmlMarks+kmlEnd;
    return kmlFull;
  }

  window.plugin.portalsExporter.bkmrkPortalFolders = function(){
    var list = window.plugin.bookmarks['bkmrk_portals'];
    var folderList = '';
    for(idFolder in list){
      var nameFolder = list[idFolder]['label'];
      if(nameFolder == 'Others'){ nameFolder = '[Portals out of folders]'; }
      folderList += '<li id="'+idFolder+'">'+nameFolder+'</li>';
    }
    return folderList;
  }

/***************************************************************************************************************************************************************/

  //---------------------------------------------------------------------------------------
  // Append the stylesheet
  //---------------------------------------------------------------------------------------
  window.plugin.portalsExporter.setupCSS = function(){
    $("<style>").prop("type", "text/css").html(
      '#portalsExpBox button{margin-top:14px;padding:2px 6px;}'
      +'#portalsExpBox textarea{display:block;width:99%;height:17px;margin:12px 0 5px;padding-top:5px;background:rgba(0,0,0,.3);color:#bbb;resize:vertical;font-size:12px;border:0;overflow:hidden;}'
      +'#portalsExpBox input[type="checkbox"]{background:none;height:auto;}'
      +'#portalsExpBox label{float:left;color:#20A8B1;}'
      +'#portalsExpBox h3{margin-top:16px;font-size:14px;}'

      +'#portalsExpBox ul, #portalsExpBox ol{padding:0;}'
      +'#portalsExpBox #convGmI ul, #portalsExpBox #convGmI ol{padding-left:21px;}'
      +'#portalsExpBox .menu li{display:block;float:left;width:33%;margin-bottom:18px;box-shadow:0 0 0 1px #20A8B1;}'
      +'#portalsExpBox .menu li a{display:block;padding:4px 0;text-align:center;}'
      +'#portalsExpBox .menu li.ui-state-active{box-shadow:0 0 0 1px gold;}'

      +'#portalsExpBox #convGmCm h2{font-size:16px;text-align:center;}'
      +'#portalsExpBox #convGmCb ul li{background:rgba(0,0,0,.25);display:block;margin-bottom:2px;padding:5px 4px;cursor:pointer;text-align:center;}'
      +'#portalsExpBox #convGmCb ul li:hover{text-decoration:underline;}'
      +'#portalsExpBox #convGmCb ul li.selected{background:#069;}'
      +'#portalsExpBox #convGmFilt{border-bottom: 1px solid gold;padding-bottom: 18px;}'
    ).appendTo("head");
  }

  //---------------------------------------------------------------------------------------
  // Append the js script
  //---------------------------------------------------------------------------------------
  window.plugin.portalsExporter.setupJS = function(){
    $('#portalsExpBox #convGmCb ul').disableSelection();

    $('#portalsExpBox #convGmCb ul').on('click', 'li', function(){
      $(this).toggleClass('selected');
      var folders = new Array();
      var i = 0;
      $('#portalsExpBox #convGmCb ul li.selected').each(function(){
        folders[i] = $(this).attr('id');
        i++;
      });
      $('#portalsExpBox #convGmCb textarea').show().text(window.plugin.portalsExporter.kmlGenFromBkmrk(folders)).attr('disabled', 'disabled');
      if(typeof android != 'undefined' && android){}else{ $('#portalsExpBox #convGmCb textarea').select(); }
    });

    $('#portalsExpBox #convGmCm #convGmFilt').toggle();
    $('#portalsExpBox #convGmCm h2').on('click', function(e){
      $(this).toggleClass('open').next('#convGmFilt').toggle();
      if($(this).hasClass('open')){ $(this).children('span').text('-'); }
      else{ $(this).children('span').text('+'); }
    });
  }

  //---------------------------------------------------------------------------------------
  // HTML element
  //---------------------------------------------------------------------------------------
  window.plugin.portalsExporter.setupContent = function(){
    plugin.portalsExporter.contentBox = ''
        +'<div id="portalsExpBox">'
          +'<ul class="menu">'
            +'<li><a href="#convGmCm">from map</a></li>'
            +'<li><a href="#convGmCb">from Bkmrk</a></li>'
            +'<li><a href="#convGmI">Istructions</a></li>'
          +'</ul>'
          +'<div style="clear:both;"></div>'

          +'<div id="convGmCm">'
            +'<h2>[<span>+</span>] Settings</h2>'
            +'<div id="convGmFilt">'
              +'<h3>Filter level portals:</h3>'
                +'<label>Use the leaflet panel beside the sidebar.</label>'
              +'<br/><div style="clear:both;"></div><h3>Filter portals owner:</h3>'
                +'<label><input type="checkbox" checked value="enl">enlightened</label>'
                +'<label><input type="checkbox" checked value="res">resistance</label>'
                +'<label><input type="checkbox" checked value="neu">neutral</label>'
              +'<br/><div style="clear:both;"></div><h3>Export data:</h3>'
                +'<label><input type="checkbox" checked value="adr">address</label>'
                +'<label><input type="checkbox" checked value="coo">latlng</label>'
                +'<label><input type="checkbox" checked value="img">images</label>'
                +'<label><input type="checkbox" checked value="clr">color team</label>'
            +'<br/><div style="clear:both;"></div></div>'

            +'<h3></h3>'
            +'<textarea></textarea>'
            +'<button onclick="window.plugin.portalsExporter.kmlGenFromMap();return false;">Reload</button>'
          +'</div>'

          +'<div id="convGmCb" style="display:none;">'
            +'<p>Select one or more folders.</p>'
            +'<ul></ul>'
            +'<p>Copy the string.</p>'
            +'<textarea placeholder="Select folders"></textarea>'
          +'</div>'

          +'<div id="convGmI" style="display:none;">'
            +'<h2>Istructions:</h2>'
            +'<ol>'
              +'<li>Copy (CTRL+C) the string;</li>'
              +'<li>Paste it in a .kml file (you can download a blank template <a href="@@INCLUDESTRING:plugins/portals-exporter-blank-kml.zip@@">here</a>) and save;</li>'
              +'<li>Import into Google Maps:<ul>'
                +'<li>Open <a href="https://maps.google.com/maps" target="_BLANK">maps.google.com</a>. Click <strong>My Places</strong> at the top left panel;</li>'
                +'<li>Create or open a map and click <strong>Edit</strong> to enter editing mode;</li>'
                +'<li>Click <strong>Import</strong> and select your .kml file;</li>'
                +'<li>Refresh Google Maps (it\'s better);</li>'
                +'<li>N.B. Google Maps automatically creates a pagination. 200 elements every page;</li>'
            +'</ul>'
              +'Import into Google Drive:<ul>'
                +'<li>Load your .kml in <a href="https://drive.google.com" target="_BLANK">drive.google.com</a>;</li>'
                +'<li>Open it (from Desktop or Mobile);</li>'
              +'</ul></li>'
            +'</ol>'
          +'</div>'
        +'</div>';
  }

/***************************************************************************************************************************************************************/

  var setup = function(){
    window.plugin.portalsExporter.setupCSS();
    window.plugin.portalsExporter.setupContent();
    $('#toolbox').append('<a onclick="window.plugin.portalsExporter.box();return false;">Portals Exporter</a>');
  }

// PLUGIN END //////////////////////////////////////////////////////////

@@PLUGINEND@@